# Generated by Django 5.1.6 on 2025-03-04 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_advisory', '0002_advisoryrequest_recommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoryrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='pending', max_length=10),
        ),
        migrations.CreateModel(
            name='AdvisoryResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisory_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='control_advisory.advisoryrequest')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
