# Generated by Django 5.1.6 on 2025-03-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_advisory', '0003_alter_advisoryrequest_status_advisoryresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisoryrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded')], default='pending', max_length=10),
        ),
        migrations.DeleteModel(
            name='AdvisoryResponse',
        ),
    ]
