# Generated by Django 5.1.6 on 2025-02-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_phone_number_expertprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_registered',
            field=models.BooleanField(default=False),
        ),
    ]
