# Generated by Django 5.1.6 on 2025-02-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_weed_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('growing_conditions', models.TextField()),
                ('common_diseases', models.TextField()),
                ('best_practices', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
