# Generated by Django 5.1.6 on 2025-03-02 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_weed_db', '0002_crop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('planting', 'Planting Stage'), ('watering', 'Watering Schedule'), ('pest_treatment', 'Pest Infestation & Treatment'), ('advisory', 'Advisory Requests'), ('fertilizer', 'Fertilizers Used'), ('sunlight', 'Sunlight & Environmental Needs'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post-Harvest Practices')], max_length=50)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle', to='pest_weed_db.crop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
