# Generated by Django 5.1.6 on 2025-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_weed_db', '0003_croplifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croplifecycle',
            name='stage',
            field=models.CharField(choices=[('planting', 'Planting Stage'), ('watering', 'Watering Schedule'), ('fertilizer', 'Fertilizers Used'), ('sunlight', 'Sunlight & Environmental Needs'), ('harvesting', 'Harvesting'), ('post_harvest', 'Post-Harvest Practices')], max_length=50),
        ),
    ]
