# Generated by Django 5.1.6 on 2025-03-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_weed_db', '0004_alter_croplifecycle_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pest',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
