# Generated by Django 5.1.6 on 2025-02-23 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pest_weed_db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PestSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest_weed_db.pest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_method', models.CharField(max_length=200)),
                ('date_applied', models.DateField()),
                ('effectiveness', models.CharField(choices=[('effective', 'Effective'), ('partially_effective', 'Partially Effective'), ('ineffective', 'Ineffective')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pest_weed_db.pest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
