# Generated by Django 5.1.6 on 2025-02-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestsighting',
            name='time',
            field=models.TimeField(blank=True, help_text='Optional exact time of sighting', null=True),
        ),
        migrations.AddField(
            model_name='treatmentoutcome',
            name='time_applied',
            field=models.TimeField(blank=True, help_text='Optional exact time of treatment', null=True),
        ),
    ]
