# Generated by Django 5.1.6 on 2025-02-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_weed_db', '0002_crop'),
        ('reports', '0003_pestsighting_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentoutcome',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatmentoutcome', to='pest_weed_db.crop'),
        ),
    ]
