# Generated by Django 5.1.6 on 2025-03-03 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_pestsighting_pest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pestsighting',
            name='control_measures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsighting',
            name='educational_nugget',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsighting',
            name='identification_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pestsighting',
            name='next_steps',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestsighting',
            name='pest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pestsighting',
            name='symptoms_recap',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pestsighting',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pestsighting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
