# Generated by Django 5.1.6 on 2025-03-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_pestsighting_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestsighting',
            name='expert',
        ),
    ]
