# Generated by Django 5.1.6 on 2025-03-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_pestsighting_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestsighting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-03-05 12:00:00'),
            preserve_default=False,
        ),
    ]
