# Generated by Django 5.1.6 on 2025-03-05 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_pestsighting_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestsighting',
            name='created_at',
        ),
    ]
